name: Selenium CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Check secret masking
        env:
          APP_PASSWORD: ${{ secrets.SAUCEDEMO_PASSWORD }}
        run: echo $APP_PASSWORD

      - name: Run Tests
        env:
          SAUCEDEMO_USERNAME: ${{ secrets.SAUCEDEMO_USERNAME }}
          SAUCEDEMO_PASSWORD: ${{ secrets.SAUCEDEMO_PASSWORD }}
        run: mvn test